sensor:
  - name: "Kegerator Scale 1"
    state_topic: "home-assistant/Input/Scale1"     
  - name: "Kegerator Scale 2"
    state_topic: "home-assistant/Input/Scale2" 
  - name: "Kegerator Scale 3"
    state_topic: "home-assistant/Input/Scale3" 
  - name: "Kegerator Scale 4"
    state_topic: "home-assistant/Input/Scale4"     
  - name: "Kegerator Scale 5"
    state_topic: "home-assistant/Input/Scale5" 
  - name: "Kegerator Temp"
    state_topic: "home-assistant/Input/KegeratorTemp"     
  - name: "Kegerator Font Temp"
    state_topic: "home-assistant/Input/FontTemp"   
  - name: "Kegerator Ambient Temp"
    state_topic: "home-assistant/Input/AmbientTemp"     
  - name: "Kegerator Watchdog"
    state_topic: "home-assistant/Input/KegWatchDog"     